### PR TITLE
Add inital apps

### PR DESCRIPTION
**Pull request by Borishbc**
## Summary

Add the following application(s) to the Circle Ecosystem Catalog:

- Company / Org: SWFT Blockchain
- Apps
  - SWFT
  - SWFT Allchain Bridge

_By submitting your name and logo, you (i) represent and warrant that you are authorized to bind
your company or protocol; and (ii) hereby grant Circle permission to use your name and logo on its
website and in its marketing materials._

### CODE REVIEW

**Comment by prakashb-circle** [comment]
@Borishbc Thanks for your submission.

Can you please add include a "description" in the yml files for your apps?

We also require all commits to be [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).  Please update your PR with signed commits. Thanks!

**Comment by Borishbc** [comment]
Ok, I added it

**Review by prakashb-circle — APPROVED** [review]

**Comment by prakashb-circle** [comment]
@Borishbc Thanks! Can you also sign the commits? Please see https://superuser.com/questions/397149/can-you-gpg-sign-old-commits for info on signing  previous commits.

This link has info on how to sign commits: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by prakashb-circle** [comment]
Added in https://github.com/circlefin/circle-ecosystem/pull/33

**Pull request closed without merging**
