### PR TITLE
bp ventures

### PR DESCRIPTION
**Pull request by antb123**
## Summary

Add the following application(s) to the Circle Ecosystem Catalog:

- Company / Org: BP Ventures
- Apps
  - bpventures

_By submitting your name and logo, you (i) represent and warrant that you are authorized to bind
your company or protocol; and (ii) hereby grant Circle permission to use your name and logo on its
website and in its marketing materials._

### CODE REVIEW

**Comment by prakashb-circle** [comment]
@antb123 Thank you for your submission. Can you please update your logo image file to conform to the following requirements?

Logos should conform to the following parameters:

Acceptable File Types: .jpg, .png, .svg
Image Size: 200 x 200 pixels
Aspect Ratio: 1:1 (square)
Max File Size: 5 MB

Thanks!

**Comment by prakashb-circle** [comment]
@antb123 We also require commits to be signed. https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by yuriescl** [comment]
As requested by @antb123, I have created another Pull Request to add BP Ventures:

https://github.com/circlefin/circle-ecosystem/pull/23

**Comment by yuriescl** [comment]
This Pull Request can be closed in favor of https://github.com/circlefin/circle-ecosystem/pull/23

**Pull request closed without merging**
