### PR TITLE
Add BetSwirl

### PR DESCRIPTION
**Pull request by RomualdH**
## Summary

Add the following application(s) to the Circle Ecosystem Catalog:

- Company / Org: BetSwirl
- Apps
  - BetSwirl

### CODE REVIEW

**Comment by reginatto** [comment]
Hey @RomualdH , thanks for the submission. Do you mind commenting how USDC is used by BetSwirl? I couldn't find any information / mention to it on the website. Also, if you could include a description of how BetSwirl defines itself, that would be great.

**Comment by RomualdH** [comment]
> Do you mind commenting how USDC is used by BetSwirl?

Hi @reginatto,
We've missed to add it on the landing page, thanks for spotting this!

It's live on our [Avalanche app](https://app.betswirl.com/analytics?c=43114), soon on Polygon:
image

**Review by prakashb-circle — APPROVED** [review]

**Comment by prakashb-circle** [comment]
@RomualdH We require commits to be signed. Can you please update your PR with signed commits? Thanks!

**Comment by RomualdH** [comment]
@prakashb-circle is it ok like that?

**Comment by prakashb-circle** [comment]
@RomualdH All commits in the PR needs to be signed. You could close this and create a new PR with just the signed commit or you could follow this process to sign all the commits in this PR: https://stackoverflow.com/questions/41882919/is-there-a-way-to-gpg-sign-all-previous-commits and do a `git push --force `

**Comment by RomualdH** [comment]
@prakashb-circle Thank you!

**Pull request merged**
